version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: mydatabase
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
